name: Grade Project Test - V1

on:
  push:
    branches:
      - 'main'

jobs:
  test-v1: # <-- this job name is totally up to you
    runs-on: ubuntu-latest # <-- usually ubuntu-latest, windows-latest, or macos-latest

    steps:
      - uses: actions/checkout@v4 # <-- every job runs on a clean runner, so you almost always start a job by checking out the code
      # This step is a GitHub action!
      
      - name: Set up Python
        uses: actions/setup-python@v5 # <-- this is a GitHub Marketplace action: https://github.com/actions/setup-python
        with:
          python-version: '3.12'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      #If you look at the top level of the repo, you will notice that it includes a requirements.txt to add the correct Python packages to your runner
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
